version: '3.9'

services:
  app:
    build: .
    ports:
      - "8080:8080"
    networks:
      - s-network
    depends_on:
      mysql:
        condition: service_healthy
    environment:
        SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/tracker_db?useSSL=false&allowPublicKeyRetrieval=true
        SPRING_DATASOURCE_USERNAME: ${SPRING_DATASOURCE_USERNAME}
        SPRING_DATASOURCE_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}
        SPRING_DATASOURCE_DRIVER_CLASS_NAME: com.mysql.cj.jdbc.Driver
        SPRING_JPA_SHOW_SQL: "true"
        SPRING_JPA_HIBERNATE_DDL_AUTO: update
        SPRING_MAIL_HOST: smtp.gmail.com
        SPRING_MAIL_PORT: 587
        SPRING_MAIL_USERNAME: ${EMAIL_USERNAME}
        SPRING_MAIL_PASSWORD: ${EMAIL_PASSWORD}
        SPRING_MAIL_PROPERTIES_MAIL_SMTP_AUTH: "true"
        SPRING_MAIL_PROPERTIES_MAIL_SMTP_STARTTLS_ENABLE: "true"
        JWT_SECRET: ${JWT_SECRET}
  mysql:
    image: mysql:8.0
    container_name: task_tracker_mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: tracker_db
    ports:
      - 3307:3306
    networks:
      - s-network
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost", "-p${MYSQL_ROOT_PASSWORD}" ]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
     - mysql_data:/var/lib/mysql
networks:
   s-network:
     driver: bridge
volumes:
    mysql_data: