name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
env:
  IMAGE_NAME:${{secrets.DOCKER_USERNAME}}/task-tracker
jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: log in to docker hub
      uses: docker/login-action@v4
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
          context: .
          push: true
          tags: ${{ env.IMAGE_NAME }}:latest
    - name: Build and push
      uses: docker/build-push-action@v7
      with:
          context: .
          push: true
          tags: name: Build and push
        uses: docker/build-push-action@v7
        with:
          context: "{{defaultContext}}:mysubdir"
          push: true
          tags: ${{ env.IMAGE_NAME }}:latest     
